[tool.poetry]
name = "tap-mssql"
version = "0.0.1"
description = "`tap-mssql` is a Singer tap for mssql, built with the Meltano Singer SDK."
readme = "README.md"
authors = ["Dan Norman"]
keywords = [
    "ELT",
    "mssql",
]
license = "MIT"

[tool.poetry.dependencies]
python = "<3.11,>=3.7.1"
requests = "^2.25.1"
singer-sdk = { version="^0.24.0" }
fs-s3fs = { version = "^1.1.1", optional = true}
pyodbc = "^4.0.39"
pymssql = "^2.2.7"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
flake8 = "^5.0.4"
darglint = "^1.8.1"
black = "^23.1.0"
pyupgrade = "^3.3.1"
mypy = "^1.0.0"
isort = "^5.11.5"
singer-sdk = { version="^0.24.0", extras = ["testing"] }
sqlalchemy-stubs = "^0.4"

[tool.poetry.extras]
s3 = ["fs-s3fs"]

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_mssql"

[tool.mypy]
python_version = "3.9"
warn_unused_configs = true
plugins = "sqlmypy"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-mssql = 'tap_mssql.tap:Tapmssql.cli'
